spring:
  application:
    name: medilab-department-service
server:
  port: 6060

department:
    fee: 450

management:
  endpoints:
    web:
      exposure:
        include: beans,mappings,metrics,loggers,shutdown,medilab-actuator
  endpoint:
    shutdown:
      enabled: true
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://medilab-department-service-mysql:3306/medilab-department-service
    url: jdbc:mysql://localhost:3306/medilab-department-service
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
  config:
    activate:
      on-profile: dev
---
spring:
  h2:
    console:
      enabled: true
      path: /h2Console
  config:
    activate:
      on-profile: stage