spring:
  application:
    name: doctor-service
  cloud:
    config:
      uri: http://localhost:8888
      
server:
  port: 6062
  
doctor:
  fee: 450


management:
  endpoints:
    web:
      exposure:
        include: refresh   
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medilab-doctor-service
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: qa
  
  datasource:
    driver-class-name: org.h2.Driver 
    url: jdbc:h2:mem:hmspro
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2Console